# Generated by Django 4.0.2 on 2022-02-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='gest_can_pause',
            new_name='guest_can_pause',
        ),
    ]
